/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#00a6e0",
        "error-container": "#93000a",
        "on-error": "#690005",
        "tertiary-container": "#00885d",
        "on-surface": "#dfe2ee",
        "surface-container": "#1c2028",
        "on-background": "#dfe2ee",
        "on-primary-container": "#0d0096",
        "tertiary": "#4edea3",
        "surface-container-high": "#262a33",
        "on-tertiary-container": "#000703",
        "outline": "#908fa0",
        "inverse-on-surface": "#2c3039",
        "surface-container-low": "#181c24",
        "surface-tint": "#c0c1ff",
        "secondary-fixed": "#c4e7ff",
        "on-secondary-container": "#00374d",
        "surface-bright": "#353942",
        "secondary": "#7bd0ff",
        "surface-dim": "#0f131c",
        "surface-container-highest": "#31353e",
        "surface-variant": "#31353e",
        "on-tertiary": "#003824",
        "inverse-surface": "#dfe2ee",
        "on-primary": "#1000a9",
        "on-tertiary-fixed": "#002113",
        "primary": "#c0c1ff",
        "outline-variant": "#464554",
        "on-tertiary-fixed-variant": "#005236",
        "on-secondary-fixed": "#001e2c",
        "on-primary-fixed-variant": "#2f2ebe",
        "primary-container": "#8083ff",
        "surface-container-lowest": "#0a0e16",
        "background": "#0f131c",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-fixed-dim": "#7bd0ff",
        "on-secondary-fixed-variant": "#004c69",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#07006c",
        "on-secondary": "#00354a",
        "primary-fixed": "#e1e0ff",
        "surface": "#0f131c",
        "tertiary-fixed": "#6ffbbe",
        "on-surface-variant": "#c7c4d7",
        "primary-fixed-dim": "#c0c1ff",
        "error": "#ffb4ab",
        "inverse-primary": "#494bd6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-sm": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "margin": "2rem",
        "gutter": "1.5rem",
        "space-xl": "2.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "margin-sm": "1rem"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "display-mobile": ["Outfit", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "numeric-metric": ["Outfit", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display": ["Outfit", "sans-serif"],
        "headline-sm": ["Outfit", "sans-serif"],
        "outfit": ["Outfit", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "display-mobile": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-md": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "numeric-metric": ["32px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-sm": ["10px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "display": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
